version: '3.2'
services:
  interactions:
    image: interactions:latest
    restart: always
    ports:
    - "25565:25565"
    volumes:
      - type: bind
        source: /docker/interactions
        target: /data
